version: '3.8'

services:
  appdb:
    image: mysql:5.7
    restart: always
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: Challenge
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: challenge
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .db/appdb.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  db_data:
